<?php

/**
 * BaseTransaction
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $type
 * @property integer $from_id
 * @property integer $to_id
 * @property integer $refer_id
 * @property integer $product
 * @property float $price
 * @property float $first_ref_fee
 * @property float $second_ref_fee
 * @property integer $ref_degree
 * @property integer $rnd
 * @property integer $expire
 * @property integer $status
 * 
 * @method integer     getId()             Returns the current record's "id" value
 * @method integer     getType()           Returns the current record's "type" value
 * @method integer     getFromId()         Returns the current record's "from_id" value
 * @method integer     getToId()           Returns the current record's "to_id" value
 * @method integer     getReferId()        Returns the current record's "refer_id" value
 * @method integer     getProduct()        Returns the current record's "product" value
 * @method float       getPrice()          Returns the current record's "price" value
 * @method float       getFirstRefFee()    Returns the current record's "first_ref_fee" value
 * @method float       getSecondRefFee()   Returns the current record's "second_ref_fee" value
 * @method integer     getRefDegree()      Returns the current record's "ref_degree" value
 * @method integer     getRnd()            Returns the current record's "rnd" value
 * @method integer     getExpire()         Returns the current record's "expire" value
 * @method integer     getStatus()         Returns the current record's "status" value
 * @method Transaction setId()             Sets the current record's "id" value
 * @method Transaction setType()           Sets the current record's "type" value
 * @method Transaction setFromId()         Sets the current record's "from_id" value
 * @method Transaction setToId()           Sets the current record's "to_id" value
 * @method Transaction setReferId()        Sets the current record's "refer_id" value
 * @method Transaction setProduct()        Sets the current record's "product" value
 * @method Transaction setPrice()          Sets the current record's "price" value
 * @method Transaction setFirstRefFee()    Sets the current record's "first_ref_fee" value
 * @method Transaction setSecondRefFee()   Sets the current record's "second_ref_fee" value
 * @method Transaction setRefDegree()      Sets the current record's "ref_degree" value
 * @method Transaction setRnd()            Sets the current record's "rnd" value
 * @method Transaction setExpire()         Sets the current record's "expire" value
 * @method Transaction setStatus()         Sets the current record's "status" value
 * 
 * @package    ProductTrading
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTransaction extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('transaction');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('type', 'integer', 1, array(
             'type' => 'integer',
             'length' => 1,
             ));
        $this->hasColumn('from_id', 'integer', 2, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 0,
             'length' => 2,
             ));
        $this->hasColumn('to_id', 'integer', 2, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 0,
             'length' => 2,
             ));
        $this->hasColumn('refer_id', 'integer', null, array(
             'type' => 'integer',
             'default' => 0,
             ));
        $this->hasColumn('product', 'integer', 2, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 0,
             'length' => 2,
             ));
        $this->hasColumn('price', 'float', null, array(
             'type' => 'float',
             'notnull' => true,
             'default' => 0,
             ));
        $this->hasColumn('first_ref_fee', 'float', null, array(
             'type' => 'float',
             'notnull' => true,
             'default' => 0,
             ));
        $this->hasColumn('second_ref_fee', 'float', null, array(
             'type' => 'float',
             'notnull' => true,
             'default' => 0,
             ));
        $this->hasColumn('ref_degree', 'integer', 1, array(
             'type' => 'integer',
             'default' => 0,
             'length' => 1,
             ));
        $this->hasColumn('rnd', 'integer', 2, array(
             'type' => 'integer',
             'default' => 0,
             'length' => 2,
             ));
        $this->hasColumn('expire', 'integer', 2, array(
             'type' => 'integer',
             'default' => 0,
             'length' => 2,
             ));
        $this->hasColumn('status', 'integer', 1, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 0,
             'length' => 1,
             ));

        $this->option('type', 'INNODB');
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}