<?php

/**
 * BaseTransaction
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $from_id
 * @property integer $to_id
 * @property integer $round
 * @property boolean $status
 * 
 * @method integer     getId()      Returns the current record's "id" value
 * @method integer     getFromId()  Returns the current record's "from_id" value
 * @method integer     getToId()    Returns the current record's "to_id" value
 * @method integer     getRound()   Returns the current record's "round" value
 * @method boolean     getStatus()  Returns the current record's "status" value
 * @method Transaction setId()      Sets the current record's "id" value
 * @method Transaction setFromId()  Sets the current record's "from_id" value
 * @method Transaction setToId()    Sets the current record's "to_id" value
 * @method Transaction setRound()   Sets the current record's "round" value
 * @method Transaction setStatus()  Sets the current record's "status" value
 * 
 * @package    ProductTrading
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTransaction extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('transaction');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('from_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 0,
             ));
        $this->hasColumn('to_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 0,
             ));
        $this->hasColumn('round', 'integer', 2, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 0,
             'length' => 2,
             ));
        $this->hasColumn('status', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => false,
             ));

        $this->option('type', 'INNODB');
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}