<?php

/**
 * GroupProductTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class GroupProductTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object GroupProductTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('GroupProduct');
    }
}