options:
 type: INNODB
 
Player:
 columns:
  id:
   type: integer(2)
   primary: true
   autoincrement: true
  name:
   type: string(32)
  profit:
   type: float
   default: 0
  token:
   type: string(255)
   notnull: true
   
Product:
 columns:
  id:
   type: integer(2)
   primary: true
   autoincrement: true
  producer:
   type: integer(2)
   notnull: true
   default: 0
  consumer:
   type: integer(2)
   notnull: true
   default: 0
  holder:
   type: integer(2)
   notnull: true
   default: 0
  cost:
   type: float
   notnull: true
   default: 0
  utility:
   type: float
   notnull: true
   default: 0

Transaction:
 columns:
  id:
   type: integer
   primary: true
   autoincrement: true
  type:
   type: integer(1)
  from_id:
   type: integer(2)
   notnull: true
   default: 0
  to_id:
   type: integer(2)
   notnull: true
   default: 0
  refer_id:
   type: integer
   default: 0
  product:
   type: integer(2)
   notnull: true
   default: 0
  price:
   type: float
   notnull: true
   default: 0
  first_ref_fee:
   type: float
   notnull: true
   default: 0
  second_ref_fee:
   type: float
   notnull: true
   default: 0
  ref_degree:
   type: integer(1)
   default: 0
  rnd:
   type: integer(2)
   default: 0
  expire:
   type: integer(2)
   default: 0
  status:
   type: integer(1)
   notnull: true
   default: 0
